steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --no-allow-unauthenticated

substitutions:
  _SERVICE: ldt-de-v2
  _REGION: asia-southeast1
  _IMAGE: gcr.io/$PROJECT_ID/ldt-de-v2:$SHORT_SHA

images:
  - ${_IMAGE}
